services:
  server:
    build:
      dockerfile: ./infra/api/Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./src/server:/home/node/app/server

  mongo:
    build: 
      dockerfile: ./infra/db/Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_USER_PASSWORD}
    ports:
      - ${MONGO_DB_HOST_PORT}:${MONGO_DB_PORT}
    volumes:
      - ./infra/db/db:/data/db
      - ./infra/db/configdb:/data/configdb

  web:
    build:
      dockerfile: ./infra/web/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - server
    volumes:
      - ./src:/home/node/app
